In [45]:
import numpy as np
import pandas as pd

In [46]:
X = np.asarray([
    [0.50],[0.75],[1.00],[1.25],[1.50],[1.75],[1.75],
    [2.00],[2.25],[2.50],[2.75],[3.00],[3.25],[3.50],
    [4.00],[4.25],[4.50],[4.75],[5.00],[5.50]])
print(X.shape)

ones = np.ones(X.shape)
X = np.hstack([ones, X])


(20, 1)


In [47]:
X

array([[1.  , 0.5 ],
       [1.  , 0.75],
       [1.  , 1.  ],
       [1.  , 1.25],
       [1.  , 1.5 ],
       [1.  , 1.75],
       [1.  , 1.75],
       [1.  , 2.  ],
       [1.  , 2.25],
       [1.  , 2.5 ],
       [1.  , 2.75],
       [1.  , 3.  ],
       [1.  , 3.25],
       [1.  , 3.5 ],
       [1.  , 4.  ],
       [1.  , 4.25],
       [1.  , 4.5 ],
       [1.  , 4.75],
       [1.  , 5.  ],
       [1.  , 5.5 ]])

In [55]:
Y = np.array([0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1]).reshape([-1, 1])
# reshape Y so it's column vector so matrix multiplication is easier
Theta = np.array([[0], [0]])
Y
Theta

array([[0],
       [0]])

In [49]:
Theta

array([[0],
       [0]])

In [50]:
mul=np.dot(X,Theta)

In [57]:
def sigmoid(a):
    return 1.0 / (1 + np.exp(-a))

def cost(x, y, theta):
    m = x.shape[0]
    h = sigmoid(np.matmul(x, theta))
    print(h)
    cost = (np.matmul(-y.T, np.log(h)) - np.matmul((1 -y.T), np.log(1 - h)))/m
    return cost

In [58]:
theta

array([1., 1., 1., 1.])

In [59]:
cost(X,Y,Theta)

[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]


array([[0.69314718]])

In [75]:
X=np.array(np.random.randn(134,3)).T

In [76]:
X.shape

(3, 134)

In [90]:
h=np.array(np.ones(134)).reshape(-1,1)

In [92]:
df=pd.DataFrame(np.random.randn(134,2),columns=['X','Y'])

In [109]:
s=np.array(df['Y'])

In [116]:
np.array(df['Y']).reshape(-1,1).shape

(134, 1)

In [88]:
grad=(X,(h-y_train))
grad1=grad

In [89]:
grad1

(array([[ 0.77563707, -0.25411081,  0.06035015, -0.48324502,  0.90862174,
         -0.66662673, -0.79397027,  0.42869419,  0.65797336, -2.11525281,
          2.81185124,  0.27753643,  0.81596626, -0.28454231,  0.07414519,
          1.06343388, -0.64750518, -0.0271248 ,  0.89270212,  0.36159974,
          0.84087979, -0.99004019,  0.44364146, -0.41362677,  1.13868621,
         -0.3434619 ,  1.37892407,  0.97763288,  0.70057582, -1.57976969,
         -0.24001395, -0.40171176, -0.31746486,  1.16415988, -0.05641469,
         -0.68983033, -1.61440377, -0.34394184,  0.54673485, -0.38114073,
          1.76540733, -0.22048692, -0.84256985,  0.0240814 ,  0.53541779,
          0.46539238,  0.04066902, -0.9654243 , -1.03588292,  0.22838854,
          0.35382349, -0.83874534, -1.33343363,  0.62754801, -0.00428939,
          0.19568433,  1.09606811,  2.31130247,  1.52179128,  0.7620457 ,
         -1.39075284, -0.71008196, -0.2783006 , -0.19305025,  2.40849605,
          0.84647934,  0.28102365,  1.

In [182]:
w=[20,30,10]
v=[40,110,20]
v_sort=sorted(v,reverse=True)
total_wt=50
value=0
weight=0
for i in range(len(w)):
    if weight<total_wt:
        weight=weight+w[v.index(v_sort[i])]
        if weight>total_wt:
            weight=weight-w[v.index(v_sort[i])]
            continue
        value=value+v_sort[i]    
    elif weight==total_wt:
        break
print("total_wt",weight)
print("total_value",value)

total_wt 50
total_value 150


In [145]:
w=[20,40,30]
v=[56,78,24]
v_sort=sorted(v,reverse=True)
w[v.index(v_sort[1])]

20